days = int(input())
hours = int(input())
minutes = int(input())
seconds = int(input())
dsecond = (days * 86400)
hsecond = (hours * 3600)
msecond = (minutes * 60)
tsecond = (dsecond + hsecond + msecond + seconds)
print (tsecond)